version: '3.9'

services:
  tiny_site_backend:
    container_name: tiny_site_backend
    image: realdevsquad/tiny_site_backend:1.0.0
    build: .
    environment:
      # Update all the envs here
      DB_URL: 'postgresql://postgres:postgres@localhost:5432/postgres?sslmode=disable'
      DB_MAX_OPEN_CONNECTIONS: '5'
      ALLOWED_ORIGINS: 'http://localhost:3000'
    ports:
      - '8000:8000'
    depends_on:
      - tiny_site_backend_db
  tiny_site_backend_db:
    container_name: tiny_site_backend_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
