name: Go Tests

on:
  pull_request:
    branches: ['*']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Copy .env.test file to environments directory
        run: cp environments/test.env .

      - name: Run go mod tidy
        run: go mod tidy

      - name: Run tests
        run: go test ./...
        env:
          ENV: test
